from turtle import * 
speed(80)


def draw(tree_color):
    penup()
    forward(100)
    begin_fill() 
    color(tree_color)
    forward(100)
    left(120)
    forward(100)
    left(120)
    forward(100)
    end_fill()
    penup()
    left(120)
    forward(40)
    pendown()
    color("brown")
    begin_fill()
    right(90)
    forward(50)
    left(90)
    forward(20)
    left(90)
    forward(50)
    right(90)
    end_fill()
    left(90)
    right(90)

draw("light green")
draw("yellow")
draw("pink")
draw("light blue")

t = Turtle()
t.screen.mainloop()